### ISSUE TITLE
[Feature Request] build with AndroidIDE

### ISSUE THREAD

**Issue by drakulaboy** [catlowlevel/ModTemplate#4]
hi, is it possible to make it so i can build it with AndroidIDE or Aide Cmods please, installed android-ndk, compiling is working, i wish i can compile it because i tried with gradle from termux but i failed, other projects with jni are compiling in AndroidIDE and Aide Cmods. Please.

**Comment by drakulaboy** [comment]
after some learning made it, thank you
![Screenshot_20231208_152028_com itsaky androidide](https://github.com/catlowlevel/ModTemplate/assets/7822898/ce65ba4d-294a-4c45-9118-7b5cb764f98c)

**Comment by catlowlevel** [comment]
If you can write guide for others, that would be great  😃

**Comment by datuan12003** [comment]
Can you guide everyone?

> sau khi học được một chút, cảm ơn bạn ![Ảnh chụp màn hình_20231208_152028_com androidide tuyệt vời](https://private-user-images.githubusercontent.com/7822898/289078615-ce65ba4d-294a-4c45-9118-7b5cb764f98c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDQ2ODMsIm5iZiI6MTcxNzk0NDM4MywicGF0aCI6Ii83ODIyODk4LzI4OTA3ODYxNS1jZTY1YmE0ZC0yOTRhLTRjNDUtOTExOC03YjVjYjc2NGY5OGMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMTQ0NjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI4YzYxODExNWEwMWQ1MWY1ODRmYTNjNjdhMGQwNjg0Y2JhMzUxN2JhZGFiNDAwYjZhMGIwZTk3YWI5YjYyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Okhhn9NnCQ6Zt0mdqHgQE2gvgyPnr76WBEzulTUwRI)

**Comment by drakulaboy** [comment]
this is the mod menu from this repo that can be compiled in AndroidIDE, check the diff
[LatestTemplateModMenu.zip](https://github.com/user-attachments/files/15759817/LatestTemplateModMenu.zip)

**Comment by drakulaboy** [comment]
if it's not forbidden and offtop, here are some mod menus that are compiling through AndroidIDE too
[Good_A-Mod-Menu-BNM.zip](https://github.com/user-attachments/files/15759853/Good_A-Mod-Menu-BNM.zip)
[Good1NormalhookExample.zip](https://github.com/user-attachments/files/15759859/Good1NormalhookExample.zip)
[Good2ExampleFieldhook.zip](https://github.com/user-attachments/files/15759863/Good2ExampleFieldhook.zip)
[GoodMrViperX-ModMenu.zip](https://github.com/user-attachments/files/15759864/GoodMrViperX-ModMenu.zip)
[NormalHook_A-Mod-Menu.zip](https://github.com/user-attachments/files/15759865/NormalHook_A-Mod-Menu.zip)
[VeryGood2ExampleFieldhook.zip](https://github.com/user-attachments/files/15759866/VeryGood2ExampleFieldhook.zip)

**Comment by datuan12003** [comment]
> đây là menu mod từ kho lưu trữ này có thể được biên dịch trong AndroidIDE, hãy kiểm tra sự khác biệt mới [nhấtTemplateModMenu.zip](https://github.com/user-attachments/files/15759817/LatestTemplateModMenu.zip)

Thank you, I will try it 😍

**Comment by datuan12003** [comment]
tôi không được may mắn rồi :'(
![Screenshot_20240616-221145_AndroidIDE](https://github.com/catlowlevel/ModTemplate/assets/130639896/51fa9ffc-3019-46a0-8a26-39157e45c34b)

**Comment by drakulaboy** [comment]
@datuan12003 what sdk and java you installed?

https://github.com/catlowlevel/ModTemplate/assets/7822898/1ff64ebd-ae3e-493e-9aba-168eaea79f1c

**Comment by datuan12003** [comment]
i use sdk 33.0.1 and java 17
