### ISSUE TITLE
[feature] add please ByNameModding

### ISSUE THREAD

**Issue by drakulaboy** [catlowlevel/ModTemplate#5]
can you add [ByNameModding](https://github.com/ByNameModding/BNM-Android) to the Mod Menu please, i tried but fail to compile

**Comment by catlowlevel** [comment]
Tell me which feature you need from BNM?

**Comment by drakulaboy** [comment]
i want to find/hook this kind of fields from the methods that doesn't have some "Update" offset
![Screenshot_20240107_084559_bin mt plus](https://github.com/catlowlevel/ModTemplate/assets/7822898/31b0e835-4bf1-45e0-a2dd-5c03656a688a)

i was looking at the example [Finding everything by names (classes, methods, fields)
[Finding everything by names](https://github.com/ByNameModding/BNM-Android/blob/master/Examples/01_Basics.cpp) but couldn't understand how to do a simple field hook

**Comment by nik2143** [comment]
You can't hook them without an instance of class

**Comment by drakulaboy** [comment]
> can't hook them

so, for this kind of classes and fields i can't use BNM?

**Comment by nik2143** [comment]
But this isn't BNM repo
You are asking on wrong repository

**Comment by Dae-Moon** [comment]
> i want to find/hook this kind of fields from the methods that doesn't have some "Update" offset ![Screenshot_20240107_084559_bin mt plus](https://private-user-images.githubusercontent.com/7822898/294742378-31b0e835-4bf1-45e0-a2dd-5c03656a688a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzUxMjMsIm5iZiI6MTcwNDg3NDgyMywicGF0aCI6Ii83ODIyODk4LzI5NDc0MjM3OC0zMWIwZTgzNS00YmYxLTQ1ZTAtYTJkZC01YzAzNjU2YTY4OGEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDgyMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNmNWNlYTVhYWM3NTRhNGRmMDExODE2MmY2ZGZiYzUyZDQxZjc0ZWY3OWY2NDY3M2RmODNlZTUwMjBjM2EyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LrMEnLsnuU5hC6VH-a9w24nq1cZS8IXEwbL3GiIe1vI)
> 
> i was looking at the example [Finding everything by names (classes, methods, fields) [Finding everything by names](https://github.com/ByNameModding/BNM-Android/blob/master/Examples/01_Basics.cpp) but couldn't understand how to do a simple field hook

To get the values of the fields, find an instance of the class (in your case, this is instance).
Copy the address of 'PlayerController_TypeInfo' from the 'script.json' generated by Il2CppDumper and add the base address to it GameAssembly.dll.
Find the offset to the static fields (usually 0x5C for 32 bit, 0x5C * 2 for 64 bit), and add the field offset to the resulting address.
Now you have the value of the field!

For example: 
![Безымянный](https://github.com/catlowlevel/ModTemplate/assets/96235598/4784be43-8928-4ddf-b335-43e12b898f6e)

it is important to note that if there is no reference to the class in the instance field, then the address will be different

**Comment by drakulaboy** [comment]
@Dae-Moon thank you for explanation, i usually search ways to mod/do it on smartphone, i was wondering how to use
the addition by BNM "utility for getting all object's fields values as json", any example?

**Comment by catlowlevel** [comment]
> i want to find/hook this kind of fields from the methods that doesn't have some "Update" offset ![Screenshot_20240107_084559_bin mt plus](https://private-user-images.githubusercontent.com/7822898/294742378-31b0e835-4bf1-45e0-a2dd-5c03656a688a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODMzNjIsIm5iZiI6MTcwNDg4MzA2MiwicGF0aCI6Ii83ODIyODk4LzI5NDc0MjM3OC0zMWIwZTgzNS00YmYxLTQ1ZTAtYTJkZC01YzAzNjU2YTY4OGEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMTAzNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTZmMTZlZGU4YmY1ZTQ4OTAyMThlN2E4MzIyOGNiN2IwZDQzY2NmOWEwNzc2YTc2MGRiMDMxNzRmYzE3NTNkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m1f2kS5rfw8XvSuULY5SZWbR2eWK61BCZF6F8rMjxMg)
> 
> i was looking at the example [Finding everything by names (classes, methods, fields) [Finding everything by names](https://github.com/ByNameModding/BNM-Android/blob/master/Examples/01_Basics.cpp) but couldn't understand how to do a simple field hook

If you want to modify the value of a field in a class that has no `Update` method, find other classes that have the same `PlayerController` class as a field, but also have an `Update` method.

For example:
```csharp
public class PlayerController 
{
    public float damageBullet; // 0x00

    // No Update method
}

public class Character 
{
    public PlayerController playerController; // 0x00

    // Has an Update function
    void Update();
}
```

the `Character` class contains both an `Update` method and a reference to the `PlayerController` class. with this information, you can hook the `Update` method. Here's an example how you'd do it with this repo:

```cpp
void Update(Il2CppObject* character){
    Il2CppObject* playerController = character->getField<Il2CppObject*>("playerController");
    float damageBullet = playerController->getField<float>("damageBullet"); // Retrieve the value from the PlayerController
    playerController->setField<float>("damageBullet", 999.f);
    return character->invoke_method("Update");
}
...
REPLACE_NAME("Character", "Update", Update);
```

you did not necessarily need an `Update` method to change a field value, it can be any method inside the same class as long as you are sure it is get called

**Comment by drakulaboy** [comment]
@catlowlevel this is the most simple and good explanation, and it really worked from the first time, thank you, means i don't need any BNM, yay! Case closed!
